	source /home/john/.config/nvim/vim-plug/plugins.vim
	source /home/john/.config/nvim/general/settings.vim
	source /home/john/.config/nvim/general/paths.vim
	source /home/john/.config/nvim/keys/mappings.vim
	source /home/john/.config/nvim/plug-config/prettier.vim
	source /home/john/.config/nvim/plug-config/coc.vim
	source /home/john/.config/nvim/plug-config/fzf.vim
	source /home/john/.config/nvim/plug-config/easymotion.vim
	source /home/john/.config/nvim/plug-config/vim-grepper.vim
	source /home/john/.config/nvim/plug-config/rainbow-brackets.vim
	source /home/john/.config/nvim/plug-config/vim-emmet.vim
	source /home/john/.config/nvim/plug-config/hexokinase.vim
