export PS1='\n[\[\e[31m\]\u\[\e[0m]:\w\]\n# '

# basic tabbed auto-complete
bind 'TAB:menu-complete'
bind '"\e[Z":menu-complete-backward'

# source all my conf files
srcRecur() {
	for arg in $1/*;
	 do
		if  [[ -d "${arg}" ]]
		 then for f in $arg/*;
			do source $f; done
		elif [[ -f "${arg}" ]]
		 then source $arg
		else echo "${arg} not valid"
		 exit 1
		fi
	 done
}

srcRecur $HOME/.config/bash/conf

unset srcRecur
