export SHELLDIR=$HOME/.config/zsh

# set theme
ZSH_THEME="bullet-train"
source $ZDOTDIR/themes/$ZSH_THEME.zsh-theme

# enable recursive tabbed auto-completion
autoload -U compinit && compinit -u

source $HOME/.config/_shell-shared/shellrc

# cust bindings
bindkey '^ ' autosuggest-accept
bindkey '^R' fzf-history-widget

source $ZDOTDIR/end-scripts.zsh

unset srcRecur SHARESHELLDIR
