export SHELL=/usr/bin/bash
export SHELLDIR=$HOME/.config/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

# basic tabbed auto-complete
bind 'TAB:menu-complete'
bind '"\e[Z":menu-complete-backward'

# set theme
eval "$(starship init bash)"

source $HOME/.config/_shell-shared/shellrc

# broken for MC, not using at the moment
# source $BPLUG/ble.sh/out/ble.sh

#default prompt
#PS1='[\u@\h \W]\$ '

unset srcRecur SHARESHELLDIR
